### ISSUE TITLE
Link de Linkedin me lleva a cuentas que no corresponden

### ISSUE THREAD

**Issue by jforni** [WalterGonzalez33/hotelSolDeSanJavierFront#10]
Los enlaces a Linkedin de Tomás Santamarina y de Isaías gius, cuando clickeo me llevan a la cuenta de Mauro Coniglio, revisar que si no tienen cuenta quede deshabilitado o no lleve a ningún lado o lleve a un error.

**Comment by MauroConiglio** [comment]
Buenas julio, ahi hice el fix de los botones y ya lo subi a main
