### ISSUE TITLE
Botones en vista celular

### ISSUE THREAD

**Issue by jforni** [WalterGonzalez33/hotelSolDeSanJavierFront#11]
Revisar que los botones tengan el mismo tamaño, principalmente hay diferencia entre el botón Iniciar Sesión y el botón Registrarse.
Adjunto imagen:
![image](https://github.com/user-attachments/assets/906324bb-7024-462e-8feb-6032d6f73402)

**Comment by MauroConiglio** [comment]
Listo esta issue Julio
